import Head from "next/head";
import Image from "next/image";
import {
	Features,
	GlobalPresence,
	Hero,
	NavBar,
	Pricing,
	Stats,
} from "../components";

export default function Home() {
	return (
		<div>
			<Head>
				<title>LaslesVPN - Best VPN Services</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<NavBar />
			{/* Hero */}
			<Hero />
			<div className="container">
				{/* Stats */}
				<Stats />
				{/* Fetures */}
				<Features />
			</div>
			<Pricing />
			<GlobalPresence />
		</div>
	);
}
